// <auto-generated />
using CineBattle.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineBattle.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122130008_AddNivelPergunta")]
    partial class AddNivelPergunta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CineBattle.Api.Model.OpcaoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerguntaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("OpcoesResposta", (string)null);
                });

            modelBuilder.Entity("CineBattle.Api.Model.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("RespostaCorretaIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Perguntas", (string)null);
                });

            modelBuilder.Entity("CineBattle.Api.Model.OpcaoResposta", b =>
                {
                    b.HasOne("CineBattle.Api.Model.Pergunta", "Pergunta")
                        .WithMany("Opcoes")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("CineBattle.Api.Model.Pergunta", b =>
                {
                    b.Navigation("Opcoes");
                });
#pragma warning restore 612, 618
        }
    }
}
